kind: pipeline
type: docker
name: amd64-test

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push

services:
  - name: database
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: osu_test
      MYSQL_USER: osu_test
      MYSQL_PASSWORD: osu_test

steps:
  - name: setup
    image: golang:1.15
    commands:
      - "go get ./..."
    when:
      branch:
        - master

  - name: build
    image: golang:1.15
    commands:
      - "go build -ldflags '-w -s' -o bin/oas_linux_amd64 cmd/cmd.go"

  - name: test
    image: golang:1.15
    environment:
      api_key:
        from_secret: osu_api_key
      osuapi_project_root: "."
    commands:
      - "go test -v ./..."

