kind: pipeline
type: docker
name: amd64-test

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - push

services:
  - name: database
    image: mariadb:10
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: osu_test
      MYSQL_USER: osu_test
      MYSQL_PASSWORD: osu_test

  - name: redis
    image: redis

steps:
  - name: unit_test
    image: golang:1.15
    environment:
      api_key:
        from_secret: osu_api_key
      osuapi_project_root: "/go/src/github.com/avimitin/osuapi"
    commands:
      - "go get ./..."
      - "go test -v -cover ./internal/..."

  - name: mysql_test
    image: golang:1.15
    commands:
      - "./intergration/scripts/mysql_test.sh"
    when:
      branch:
        - master

  - name: redis_test
    image: golang:1.15
    commands:
      - "./intergration/scripts/redis_test.sh"
    when:
      branch:
        - master
