kind: pipeline
type: docker
name: amd64-test

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: /src/github.com/avimitin/osuapi

trigger:
  event:
    - push

services:
  - name: database
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: osu_test
      MYSQL_USER: osu_test
      MYSQL_PASSWORD: osu_test

steps:
  - name: server_test
    image: golang:1.15
    environment:
      api_key:
        from_secret: osu_api_key
      osuapi_project_root: "/go/src/github.com/avimitin/osuapi"
    commands:
      - "go get ./..."
      - "echo 'waiting for mariadb setting up'"
      - "sleep 15"
      - "go build -ldflags '-w -s' -o bin/oas_linux_amd64 cmd/cmd.go"
      - "go test -v ./..."
    when:
      branch:
        - master

